### ISSUE TITLE
Admonition formatting looks odd in live preview mode—huge spacing

### ISSUE THREAD

**Issue by lukthony** [valentine195/obsidian-admonition#141]
This is in a fresh vault, Admonition is the only plug-in installed, Obsidian v0.13.4, Admonition v6.7.2

Preview(expected behavior):
<img width="750" alt="Screen Shot 2021-12-22 at 5 27 02 PM" src="https://user-images.githubusercontent.com/65358837/147166177-823d3c5c-830d-4903-838f-9b3f602afb4f.png">

Live Preview (actual behavior):
<img width="755" alt="Screen Shot 2021-12-22 at 5 26 56 PM" src="https://user-images.githubusercontent.com/65358837/147166222-eb7a0d3c-8abe-437b-b3a2-1ea8be9811a8.png">

**Comment by red0orange** [comment]
I also meet this problem.

**Comment by valentine195** [comment]
This is likely just a plugin CSS problem, will investigate and fix once I get a chance.

**Comment by red0orange** [comment]
Thank you and Merry Christmas!

**Comment by GOUKOU007** [comment]
This problem can be  temporarily fixed by add following css snippet in snippet folder:
```css
.is-live-preview .admonition-content>p {
    margin: 0px;
}

.is-live-preview .admonition-content>p:first-child {
    margin-top: 16px;
}

.admonition-content>p:last-child {
    margin-bottom: 16px;
}
```

**Comment by phlind** [comment]
> This problem can be temporarily fixed by add following css snippet in snippet folder:
> 
> ```css
> .is-live-preview .admonition-content>p {
>     margin: 0px;
> }
> 
> .is-live-preview .admonition-content>p:first-child {
>     margin-top: 16px;
> }
> 
> .admonition-content>p:last-child {
>     margin-bottom: 16px;
> }
> ```

Unfortunately, that doesn't work for me.

**Comment by tim-hilde** [comment]
For me neither

**Comment by valentine195** [comment]
Okay, a partial fix should be up in 6.7.4. Lists still have a bit of wonkiness to them, but it should look better.

**Comment by tim-hilde** [comment]
I still have the problem esp. with the minimal theme

**Comment by valentine195** [comment]
> I still have the problem esp. with the minimal theme

Can you show me an example of the problem you are seeing?

Also, I will investigate more, but I target the base Obsidian theme for the most part. I cannot accommodate all themes.

**Comment by phlind** [comment]
I'm seeing this with the Minimal theme:

![Bildschirmfoto 2022-01-07 um 14 41 14](https://user-images.githubusercontent.com/30386310/148552380-f512801b-5e8b-40cd-a8a1-b8d528bf0a2e.png)

In the default theme it's not as strong, but still partly present:

![Bildschirmfoto 2022-01-07 um 14 44 27](https://user-images.githubusercontent.com/30386310/148552553-143e1b5e-c0ea-45ae-a582-410bee5fa0f4.png)

**Comment by valentine195** [comment]
Please update the plugin and try again... both links and the issues you've seen with Minimal should be improved.

**Comment by phlind** [comment]
Yes, it's fixed not, thanks!
